# Generated by Django 4.2.2 on 2023-07-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Nome Categoria', max_length=99, unique=True),
        ),
    ]
