# Generated by Django 4.2.2 on 2023-07-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_rename_data_criacao_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Nome Categoria', max_length=99, unique=True),
        ),
    ]
