# Generated by Django 4.2.2 on 2023-06-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
