# Generated by Django 4.2.2 on 2023-06-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_bar',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
