# Generated by Django 4.2.2 on 2023-07-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logstorestock',
            name='type_movement',
            field=models.IntegerField(choices=[(1, 'Entrada'), (2, 'Saida'), (3, 'Transferencia'), (4, 'Saida Manual')], default=1),
        ),
        migrations.AlterField(
            model_name='logwarehouse',
            name='type_movement',
            field=models.IntegerField(choices=[(1, 'Entrada'), (2, 'Saida'), (3, 'Transferencia'), (4, 'Saida Manual')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], default=1),
        ),
    ]
