# Generated by Django 4.2.2 on 2023-07-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_logstorestock_type_movement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logwarehouse',
            name='product',
        ),
        migrations.RemoveField(
            model_name='logwarehouse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storestock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='product',
        ),
        migrations.DeleteModel(
            name='LogStoreStock',
        ),
        migrations.DeleteModel(
            name='LogWarehouse',
        ),
        migrations.DeleteModel(
            name='StoreStock',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
