# Generated by Django 4.2.2 on 2023-07-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_deleted',
        ),
    ]
