# Generated by Django 4.2.2 on 2023-06-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='User Teste', max_length=20, unique=True)),
                ('name', models.CharField(default='Nome Teste', max_length=20)),
                ('cpf', models.CharField(default='999.999.999-99', max_length=11, unique=True)),
                ('email_collaborator', models.EmailField(default='teste@teste.com', max_length=254, unique=True)),
                ('password', models.CharField(default='1111111111', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
