# Generated by Django 4.2.2 on 2023-07-11 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Collaborator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='email_collaborator',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='username',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='cpf',
            field=models.CharField(default='999.999.999-99', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(default='Nome Teste', max_length=255),
        ),
    ]
