# Generated by Django 4.2.2 on 2023-06-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='email_collaborator',
            new_name='email',
        ),
    ]
