# Generated by Django 4.2.2 on 2023-06-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborator', '0002_rename_email_collaborator_collaborator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='cpf',
            field=models.CharField(default='999.999.999-99', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=254),
        ),
    ]
