# Generated by Django 4.2.2 on 2023-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborator', '0002_remove_collaborator_email_collaborator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='active',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], default=1),
        ),
    ]
