# Generated by Django 4.2.2 on 2023-07-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborator', '0003_alter_collaborator_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='cod_bar_auth',
            field=models.CharField(default='Nome Teste', max_length=15),
        ),
    ]
