# Generated by Django 4.2.2 on 2023-06-25 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Collaborator', '0003_alter_collaborator_cpf_alter_collaborator_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='username',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
