# Generated by Django 4.2.2 on 2023-07-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborator', '0005_alter_collaborator_cod_bar_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='cod_bar_auth',
            new_name='cod_auth',
        ),
    ]
