# Generated by Django 4.2.2 on 2023-07-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_is_deleted_and_more'),
        ('Collaborator', '0002_remove_collaborator_email_collaborator_and_more'),
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='fk_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='fk_purchase',
            new_name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='fk_colaborattor',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='fk_collaborator',
        ),
        migrations.AddField(
            model_name='purchase',
            name='collaborator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Collaborator.collaborator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(related_name='purchases', through='Purchase.PurchaseItem', to='Product.product'),
        ),
    ]
