# Generated by Django 4.2.2 on 2023-07-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_rename_fk_product_purchaseitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_utils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_marketing', models.CharField(max_length=50)),
                ('email_rh', models.CharField(max_length=50)),
            ],
        ),
    ]
