# Generated by Django 4.2.2 on 2023-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_info_utils'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('use_tls', models.BooleanField(default=True)),
            ],
        ),
    ]
