# Generated by Django 4.2.2 on 2023-07-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_remove_purchaseitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
